erDiagram
  ROAR_USER ||--o{ ROAR_RUN : has
  ROAR_RUN ||--o{ ROAR_TRIAL : writes
  ROAR_TASK ||--o{ ROAR_VARIANT : defines
  ROAR_RUN }o--|| ROAR_TASK : task
  ROAR_RUN }o--|| ROAR_VARIANT : variant
  ROAR_TASK_PA }o--|| ROAR_APP_KIT : uses
  ROAR_TASK_SWR }o--|| ROAR_APP_KIT : uses
  ROAR_TASK_SRE }o--|| ROAR_APP_KIT : uses

  ROAR_USER {
    string id
    string assessmentPid
    string userType
  }
  ROAR_TASK {
    string taskId
    string name
  }
  ROAR_VARIANT {
    string variantId
    string name
  }
  ROAR_RUN {
    string id
    string taskId
    string variantId
    boolean completed
  }
  ROAR_TRIAL {
    string id
    string assessment_stage
    boolean correct
  }
  ROAR_APP_KIT {
    string methods_startRun_updateTaskParams_updateUser_writeTrial_finishRun_updateEngagementFlags_addInteraction_abortRun_validateParameters
  }
  ROAR_TASK_PA {
    string methods_startRun_updateTaskParams_updateUser_writeTrial_finishRun_updateEngagementFlags_addInteraction_abortRun
  }
  ROAR_TASK_SWR {
    string methods_startRun_updateTaskParams_updateUser_writeTrial_finishRun_updateEngagementFlags_addInteraction_abortRun_validateParameters
  }
  ROAR_TASK_SRE {
    string methods_startRun_updateTaskParams_updateUser_writeTrial_finishRun_updateEngagementFlags_addInteraction_abortRun_validateParameters
  }
