name: Update Core Tasks Dependency

on:
  repository_dispatch:
    types: [update-core-tasks]

jobs:
  update-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.LEVANTE_BOT_APP_ID }}
          private_key: ${{ secrets.LEVANTE_BOT_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Update core-tasks dependency
        run: |
          npm install @levante-framework/core-tasks@${{ github.event.client_payload.version }}

      - name: Commit and push changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add package.json package-lock.json
          git diff --staged --quiet || git commit -m "chore: update core-tasks to ${{ github.event.client_payload.version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
